(labels ((split-at-with (lst)
               (do ((elem (pop lst)
			  (pop lst))
	            (acc nil (cons elem acc)))
	          ((eql elem 'with) (values (nreverse acc)
		  			    (copy-list lst))))))
  (defmacro does (&rest args)
    (multiple-value-bind (body fns) (split-at-with lst)
     `(labels (,@fns)
        ,@body))))
